services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  graphql:
    build: .
    environment:
      PORT: 4000
      GRAPHQL_PATH: /graphQL
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URL: mongodb://root:example@mongo:27017/

    ports:
      - "4000:4000"